Jnuit.xml file creation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -91,15 +91,37 @@ jobs:
             chromedriver --version
           name: Check install
       - run:
-          name: run tests
+          name: Run Selenium Tests
           command: |
-            python -m venv venv
-            . venv/bin/activate
-            pip install -r requirements.txt
-            mkdir test-results
-            pytest --junitxml=test-results/junit.xml tests/
+            whereis chrome
+            pwd
+            ls -lrtha
+            chmod 777 build.sh
+            ./build.sh 
+            ls -lrtha
+            cd tests
+            chmod 777 selenium_driver_code.py
+            python selenium_driver_code.py
+            ls -la
+      - run:
+          name: Store Test Results
+          command: |
+            pwd
+            ls -la
+            mkdir test-results   
+            ls -la         
+            cp -r tests/test_results.xml test-results/
       - store_test_results:
           path: test-results
+      - run:
+          name: Check Test Results
+          command: |
+            if grep -q "FAILED" test-results/*.xml; then
+              echo "Tests failed, triggering rollback"
+              exit 1
+            else
+              echo "Tests passed"
+            fi
 
   rollback:
     working_directory: ~/Flask-calculator
@@ -112,6 +134,17 @@ jobs:
             az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
             az account set --subscription $AZURE_SUBSCRIPTION_ID
             az webapp deployment source config-zip -g $AZURE_RG_NAME -n $AZURE_WEBAPP_NAME --src previous-stable.zip
+
+  rollback_timeout:
+    working_directory: ~/Flask-calculator
+    docker:
+      - image: cimg/python:3.9.9
+    steps:
+      - run:
+          name: Timeout Check for Rollback
+          command: |
+            sleep 600  # Wait for 10 minutes
+            echo "No approval received for rollback. Proceeding to the next step."
 
 workflows:
   build_and_test_deploy:
@@ -135,3 +168,9 @@ workflows:
             branches:
               only: stage
           type: approval
+      - rollback_timeout:
+          requires:
+            - rollback
+          filters:
+            branches:
+              only: stage
